### PR TITLE
chore: move ci to node 16

### PR DESCRIPTION
**Pull request by inian**

### CODE REVIEW

**Comment by soedirgo** [comment]
I'll try and fix the CI error on a separate PR

**Review by soedirgo — APPROVED** [review]

**Comment by inian** [comment]
@soedirgo it was due to typedoc. Upgrading it to the latest version fixed it. Docs are generating correctly. The HTML looks correct. The spec.json has slightly different formatting though, not sure if this will affect how docs are generated downstream.

**Comment by soedirgo** [comment]
Ah cheers 👍

**Comment by inian** [comment]
Blocked until @kiwicopple confirms that the spec.json generated is compatible with the new docs site

**Pull request merged**
